version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_peliculas
    environment:
      POSTGRES_DB: pelicula
      POSTGRES_USER: pelicula
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pelicula_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pelicula
      SPRING_DATASOURCE_USERNAME: pelicula
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres_data:
